config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
    resources :comments
  end
  resources :tags
  
  # root: "articles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :taggings
    has_many :comments
    has_many :tags, through: :taggings
    has_one_attached :image
    # validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
    

    def tag_list
        self.tags.collect do |tag|
          tag.name
        end.join(", ")
      end

      def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
        self.tags = new_or_found_tags
      end
end

app/models/comment.rb
class Comment < ApplicationRecord
 # belongs_to :user
  belongs_to :article
  belongs_to  :parent, class_name: 'Comment', optional: true
  has_many    :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  include ActiveStorage::SetCurrent



  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @articles = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :tag_list, :image, :comment)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  def new 
    @article = Article.fine(params[:article_id])
    @comment = @article.comments.new(parent_id: params[:parent_id])

  end

  def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.new(comment_params)
      redirect_to article_path(@article)    
  end

  def index
      @comments = Comment.all
    end
  

  def destroy
      @post = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:name, :comment, :article_id, :parent_id, :user_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def show
        @tag = Tag.find(params[:id])
    end

    def index 
       @tags = Tag.all  
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

    def article_params
        params.require(:article).permit(:title, :description, :tag_list, :image)
      end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <div class="card"> 
  <%=image_tag article.image.url%>
  
  <div class="container">    
    <h2 class=""><%= article.title %></h2>
    <p class=""><%= article.description %></p>
    <%= article.comments.count%> Comments
    <%= article.comments.name %>

    <p>Tags:</p> <span class="tag-cloud"><%=article.tag_list%></span>

  </div>
</div>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>


      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="">
   <div class="">
    <div class="">
    <%= f.label :tags %><br>
    <%= f.text_field :tag_list %>

  <div class="">
    <%= f.label :title, style: "display: block" %>
    <%= f.text_field :title %>
  </div>

  <div class="">
    <%= f.label :description, style: "display: block" %>
    <%= f.text_area :description, cols: 100, rows: 10 %>
  </div>

  <div class="">
  <%= f.label :image, "Attach an Image"%><br />
  <%= f.file_field :image %>
</div>

<div>
<%= f.submit %>
</div>
</div>
</div>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>All Articles</h1>


<div class="articles">
<%  @articles.each  do |article| %>
      <%= render article %> 
      <%= link_to "Show this article", article, class: 'link-to-text-color' %><br>
      <%= link_to "Add Comment", new_article_comment_path(article) %>
      </div>
  <% end %>

<%= link_to "New article", new_article_path, class: 'link-to-text-color' %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path, class: 'link-to-text-color'%>
</div>

app/views/articles/show.html.erb
<div class="">
<p style="color: green"><%= notice %></p>
<%= render @article %>
<div class="image">
</p>
</div>
</div>
<div>

</div>
</div>
<div class="card my-1">
<div class="card-body">
<p class="font-weight-bold">Comments</p>
<%= form_with(model: [@article, @article.comments.build]) do |f| %>
    <div class="form-group">
    <%= f.label 'New comment' %>
    <%= f.text_area :comment, class: 'form-control' %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
    </div>
    </div>
    <%= render @article.comments %>
    <%= link_to "Edit this article", edit_article_path(@article), class: 'link-to-text-color'%> |
    <%= link_to "Back to articles", articles_path, class: 'link-to-text-color'%>
    
    <%= button_to "Destroy this article", @article, method: :delete %>
    </div>

app/views/comments/_comment.html.erb
# # <% unless comment.parent_id || !comment.persisted? %>
#   <div class="card">
#     <div class="card-body">
#       <%= comment.comment %>
#       <%= link_to 'reply', new_article_comment_path(@article, parent_id: comment.id), remote: true, class: 'd-block' %>
#       </div>
#   </div>
#   <% if comment.replies.any? %>
#     <% comment.replies.each do |reply| %> 
#       <%= render partial: 'comments/reply', locals: { reply: reply } %>
#     <% end %>
#   <% end %>
#   <div id="reply-form-<%= comment.id %>"></div>
# <% end %>




<%= comment.comment %>
      <%= link_to 'reply', new_article_comment_path(@article, parent_id: comment.id), remote: true, class: 'd-block' %>
      </div>
  </div>
  <% if comment.replies.any? %>
    <% comment.replies.each do |reply| %> 
      <%= render partial: 'comments/reply', locals: { reply: reply } %>
    <% end %>
  <% end %>

  <div id="reply-form-<%= comment.id %>"></div>

app/views/comments/_form.html.erb
<%= form_for([@comment.article,@comment]) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
  
        <ul>
          <% comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :comment %>
      <%= form.text_area :comment %>
    </div>
  
    <div class="field">
      <%= form.label :article_id %>
      <%= form.number_field :article_id %>
    </div>
  
    <div class="field">
      <%= form.label :parent_id %>
      <%= form.number_field :parent_id %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/comments/_reply.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= reply.body %>
  </div>
</div>

app/views/comments/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_with(model: [@article, @comment]) do |f| %>
      <%= f.hidden_field :parent_id %>
      <div class="form-group">
        <%= f.label 'Reply' %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', article_path(@article), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<ul>
<% @comments.each do |c|%>
  <li><%= c.user.email%> says "<%= c.comment%>" about this article: <strong><%= link_to c.article.title, article_path(c.article_id) %></strong></li>
  
<% end %>

</ul>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', article_comments_path %>

app/views/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>")
.innerHTML= ("<%= j render 'reply_form', comment: @comment %>")

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @comment.parent_id %>
</p>

<%= link_to 'Edit', edit_article_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300&display=swap" rel="stylesheet">
  </head>

  <body>
  <div class="navbar">
  <a class="active" href="/articles"><img width="48" height="48" src="https://img.icons8.com/color/48/home--v1.png" alt="home--v1"/> Home</a> 
  <a href="#"><img width="48" height="48" src="https://img.icons8.com/external-vitaliy-gorbachev-flat-vitaly-gorbachev/58/external-search-food-delivery-vitaliy-gorbachev-flat-vitaly-gorbachev.png" alt="external-search-food-delivery-vitaliy-gorbachev-flat-vitaly-gorbachev"/>Search</a> 
  <a href="#"><img width="48" height="48" src="https://img.icons8.com/external-flatart-icons-flat-flatarticons/64/external-email-contact-us-flatart-icons-flat-flatarticons.png" alt="external-email-contact-us-flatart-icons-flat-flatarticons"/>Contact</a> 
  <a href="#"><img width="48" height="48" src="https://img.icons8.com/color/48/import.png" alt="import"/>Login</a>
  
  <p class="navbar-text float-right">
  <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link"  %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
  <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
  <% end %>
  </p>
  </div>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>